use gifthub;
-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 09:57:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gifthub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gifthub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gifthub` DEFAULT CHARACTER SET utf8 ;
USE `gifthub` ;

-- -----------------------------------------------------
-- Table `gifthub`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gifthub`.`USUARIO` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dpi` VARCHAR(45) NOT NULL,
  `edad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabla para usuarios ';


-- -----------------------------------------------------
-- Table `gifthub`.`CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gifthub`.`CUENTA` (
  `id_cuenta` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) ,
  INDEX `fk_CUENTA_USUARIO_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_CUENTA_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gifthub`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifthub`.`GIFTCARDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gifthub`.`GIFTCARDS` (
  `id_giftcards` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(500) NULL,
  `charge_rate` DECIMAL NULL,
  `activa` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_giftcards`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifthub`.`AVAILABILITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gifthub`.`AVAILABILITY` (
  `id_valor` INT NOT NULL,
  `total` INT NOT NULL,
  `id_giftcards` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_valor`),
  INDEX `fk_AVAILABILITY_GIFTCARDS1_idx` (`id_giftcards` ASC),
  CONSTRAINT `fk_AVAILABILITY_GIFTCARDS1`
    FOREIGN KEY (`id_giftcards`)
    REFERENCES `gifthub`.`GIFTCARDS` (`id_giftcards`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;